[package]
name = "interface-trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.5"
interface-derive = { path = "../interface-derive" }
hex = "0.4.3"