[package]
name = "fvm-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fil_actors_runtime = { path = "./runtime", features = ["test_utils", "fil-actor"] }
primitives = { path = "primitives" }
interface-trait = { version = "0.1.0", path = "interface-trait" }
interface-derive = { version = "0.1.0", path = "interface-derive" }

[workspace]
members = [
    "runtime",
    "primitives",
    "example",
    "interface-derive",
    "interface-trait",
]
