[package]
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
description = "System actors for the Filecoin protocol"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "fil_actors_runtime"
repository = "https://github.com/filecoin-project/builtin-actors"
version = "0.0.1"

[dependencies]
base64 = "0.13.0"
byteorder = "1.4.3"
castaway = "0.2.2"
cid = {version = "0.10.1", default-features = false, features = ["serde-codec"]}
frc42_dispatch = "5.0.0"
fvm_ipld_amt = { git = "https://github.com/filecoin-project/ref-fvm", branch = "upgrade-fvm" }
fvm_ipld_hamt = { git = "https://github.com/filecoin-project/ref-fvm", branch = "upgrade-fvm" }
fvm_shared = { git = "https://github.com/filecoin-project/ref-fvm", branch = "upgrade-fvm", features = ["crypto"] }

indexmap = {version = "1.8.0", features = ["serde-1"]}
integer-encoding = {version = "3.0.3", default-features = false}
lazy_static = "1.4.0"
log = "0.4.14"
num-derive = "0.3.3"
num-traits = "0.2.14"
serde = {version = "1.0.136", features = ["derive"]}
thiserror = "1.0.30"
unsigned-varint = "0.7.1"
# enforce wasm compat
anyhow = "1.0.56"
blake2b_simd = "1.0"
fvm_ipld_blockstore = { git = "https://github.com/filecoin-project/ref-fvm", branch = "upgrade-fvm" }
fvm_ipld_encoding = { git = "https://github.com/filecoin-project/ref-fvm", branch = "upgrade-fvm" }
fvm_sdk = { git = "https://github.com/filecoin-project/ref-fvm", branch = "upgrade-fvm", optional = true }

getrandom = {version = "0.2.3", features = ["js"]}
hex = {version = "0.4.3", optional = true}
itertools = "0.10"
multihash = {version = "0.18.1", default-features = false}
paste = "1.0.9"
rand = "0.7.3"
regex = "1"
serde_repr = "0.1.8"
serde_tuple = "0.5.0"

[dependencies.sha2]
version = "0.10"

[dev-dependencies]
derive_builder = "0.10.2"
hex = "0.4.3"

[features]
default = []
fil-actor = ["fvm_sdk"]

# Enable 2k sectors
sector-2k = []
# Enable 8m sectors
sector-8m = []
# Enable 512m sectors
sector-512m = []
# Enable 32g sectors
sector-32g = []
# Enable 64g sectors
sector-64g = []
# Enable the "default" sectors types.
sector-default = ["sector-64g", "sector-32g"]

# Reduce min verified deal size from 1MiB to 256B
small-deals = []
# Reduce pre-commit delay from 150 epochs, to 10.
short-precommit = []

# Lower the minimum power requirement to 2k
min-power-2k = []
# Lower the minimum power requirement to 2g
min-power-2g = []

# no collateral for deals (for testing)
no-provider-deal-collateral = []

# fake proofs (for testing)
fake-proofs = []

test_utils = ["hex", "multihash/sha2"]
